### ISSUE TITLE
[Bug]: ERROR: Got 400 error attempting to POST to submitTransaction

### ISSUE THREAD

**Issue by simonebaracchi** [vzhd1701/enex2notion#100]
### enex2notion version

0.2.26

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10 Pro

### Bug description

When trying to upload my notes, I get this error. Retrying doesn't seem to help.

Testing the note (without `--token`) doesn't show anything significant.

In Notion I can see a page "stub" created each attempt I make, but the note just has the title with a "[UNFINISHED UPLOAD]" at the end, and nothing in it. The original note had some text and a picture. 

### Log excerpt

```shell
.\enex2notion.exe --token omitted-export-token export/
INFO: 'Evernote ENEX Import' page found
INFO: Processing directory 'export'...
INFO: Processing notebook 'omissis'...
INFO: Uploading note 1 out of 32 '90 days plan'
 50%|█████████████████████                     | 2/4 [00:01<00:01,  1.12block/s]ERROR: Got 400 error attempting to POST to submitTransaction, with data: {
  "operations": [
    {
      "id": "e09fb5c3-a00a-406c-9b2d-072f26f829fc",
      "path": [
        "file_ids",
        0
      ],
      "args": "2-fe4b-4d84-bc22-0f13884b2074",
      "command": "set",
      "table": "block"
    },
    {
      "args": {
        "last_edited_by_id": "eb9705d0-073c-47df-bfb6-cad5cd2b74fe",
        "last_edited_by_table": "notion_user",
        "last_edited_time": 1693774925399
      },
      "command": "update",
      "id": "e09fb5c3-a00a-406c-9b2d-072f26f829fc",
      "path": [],
      "table": "block"
    }
  ]
}
DEBUG: Network error: Something went wrong. (400)
WARNING: Failed to upload note 'omitted note name' to Notion! Retrying...
```
```

**Comment by kosinski77** [comment]
Me too. Happens for every import. MacOS Ventura 13.5.

**Comment by kshen000** [comment]
I have the same issue. Looks like it failed on pages that have embedded PDF files.

**Comment by simonebaracchi** [comment]
Seems to be a PNG image in my case.

**Comment by marcogerstmann** [comment]
I have the exact same issue. Happens every time it imports a note with an image in it (directly on the image block).

**Comment by xtayaitak** [comment]
me too

**Comment by ChetanArvindPatil** [comment]
Same error as @simonebaracchi. Notes with images.

Cc: @vzhd1701

**Comment by jonathan-943** [comment]
I have the same issue. Newest Python version, the first note already fails with a 400 bad request.
