### ISSUE TITLE
[Bug]: parse error

### ISSUE THREAD

**Issue by craigwinkler** [vzhd1701/enex2notion#101]
### enex2notion version

0.3.0

### What OS are you using?

MacOS

### OS Version / Linux distribution

MacOS 14.0

### Bug description

In general enex2notion works terrifically well, thank you. 

In some Evernote notebooks I get a parse error at the beginning of the process. Even in verbose mode there is no information beyond that.

In each case a bunch of notes get correctly imported, but way less than the source .enex file contains. Is there any more information on what the parsing problem was? I can't work out how to rectify a hidden issue.

In the log info provided below for "Personal" the original file contains 4569 notes, NOT the 284 that enex2notion thinks.

### Log excerpt

```shell
WARNING: No token provided, dry run mode. Nothing will be uploaded to Notion!
INFO: Processing notebook 'Personal'...
WARNING: 'Personal.enex' file parsed with errors
DEBUG: Personal.enex:571373:95:xmlSAX2Characters: huge text node
DEBUG: 'Personal' notebook contains 284 note(s)
DEBUG: Parsing note 'Mindy G Cleaning'
DEBUG: Parsing note 'Electrolux EBE5307SA Refrigerator-Freezer manual'
...etc
```

**Comment by vzhd1701** [comment]
When you use --verbose flag, all parsing errors are printed right after "file parsed with errors" warning. This is your parse error on line 571373, column 95 in Personal.enex:
```
DEBUG: Personal.enex:571373:95:xmlSAX2Characters: huge text node
```

**Comment by zzamboni** [comment]
@vzhd1701 Thanks also from my side for enex2notion!

Thanks for the explanation - I'm getting the same error, and looking at the location in my ENEX file, it's in the middle of a `<data encoding="base64">` block in a note that contains a few large PDF attachments. I guess this is what's causing the "huge text node" error? 

Is there a way to increase the maximum allowed node size, or some other workaround for this?

**Comment by zzamboni** [comment]
I've just submitted PR #102 to fix this bug and another one I found, where some notes that had just a title and no content were failing.

**Comment by vzhd1701** [comment]
This should be fixed in the new version. Thanks again, @zzamboni! Homebrew version will be updated in a few hours.
