### ISSUE TITLE
[Feature request]: Add custom page tag

### ISSUE THREAD

**Issue by stdavis** [vzhd1701/enex2notion#23]
### Suggestion

It would be awesome to have the option to pass an option to set a custom tag for each page created in Notion by this tool. So that I could do something like this:
```
enex2notion . --tag imported-from-evernote
```

Thanks for the AWESOME tool! I've been waiting forever for Notion to fix their import from Evernote. I'm very hopeful that this tool will finally allow me to make the switch.

**Comment by vzhd1701** [comment]
Could you please elaborate on the use case for this feature? As far as I know Notion doesn't retain tags when you move page between databases.

**Comment by stdavis** [comment]
I just wanted every page that I imported from Evernote to have a tag named `imported-from-evernote` when it is created in Notion. Just to help me know which pages were imported and which I have created within Notion.

**Comment by vzhd1701** [comment]
When you import to Notion with `enex2notion`, it creates a new database and puts all notes there. I mean, sure, I can make it add a tag for each imported note, but that tag will be lost if you move the page to another database since Notion doesn't have a global tag system as Evernote does. So you will end up with an "Imported from evernote" database where each note is tagged as "imported-from-evernote", which is usable within that database only.

**Comment by stdavis** [comment]
Yes, I imported one database at a time so that I didn't have to reorganize things. But I was able to hack the code to add the tag for my own work. I imported something like 10,000 notes from Evernote. This tool was AWESOME! If this enhancement doesn't make sense for the project, no worries. Feel free to close the issue. It was just a suggestion.

**Comment by vzhd1701** [comment]
Happy to hear that! If you found this feature useful then it's worth adding to the project.

By the way, did you find a way to move notes between databases while retaining their tags in Notion?

**Comment by stdavis** [comment]
> By the way, did you find a way to move notes between databases while retaining their tags in Notion?

I don't think so. IIRC I altered your tool to accept a database name as a parameter and imported one notebook to one database at a time using a script.
