### ISSUE TITLE
[Bug]: If the last edit time is null, the date is still the uploading date of Notion

### ISSUE THREAD

**Issue by git-gitgit** [vzhd1701/enex2notion#30]
### enex2notion version

0.2.10

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 11

### Bug description

Thanks for the work on #29. 
There are some notes in Evernote. When a new note is created and the content is quickly copied into, the last edit time will be null.
When the last edit time is null in metadate, the notion will still use the uploading date as the updated date.
My understanding is that if the last edit time is null, we could use created date as updated date.

**Comment by vzhd1701** [comment]
Fixed in [v0.2.11](https://github.com/vzhd1701/enex2notion/releases/tag/v0.2.11)
