### ISSUE TITLE
[Feature request]: Make enex2notion keep Evernote's internal URLs in metadata

### ISSUE THREAD

**Issue by sypianski** [vzhd1701/enex2notion#37]
### Suggestion

I would sometimes be happy to return to the original note in Evernote (especially when the note was imported with an error). I would appreciate being able to click in Notion and be directly redirected to the right place in Evernote.

**Comment by vzhd1701** [comment]
I am afraid this is not possible. Evernote original note IDs are not retained in `*.enex` files.
