### ISSUE TITLE
[Bug]: Failed to upload note

### ISSUE THREAD

**Issue by lbossle** [vzhd1701/enex2notion#38]
### enex2notion version

0.2.13

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 11

### Bug description

The tool suddenly stopped working. Yesterday I successfully uploaded a few notebooks. Today I wanted to continue but it isn't able to upload the data. The "Evernote ENEX Import" page and the page for the notebook is created, but then the programm fails with the attatched logs.

Thanks for developing this amazing tool :smil

### Log excerpt

```shell
INFO: Creating 'Evernote ENEX Import' page...
INFO: Processing directory 'evernote'...
INFO: Processing notebook 'Notebook'...
INFO: Uploading note 1 out of 10 'Note'
DEBUG: Creating new page for note 'Note'
WARNING: Failed to upload note 'Note' to Notion! Retrying...
DEBUG: Creating new page for note 'Note'
WARNING: Failed to upload note 'Note' to Notion! Retrying...
DEBUG: Creating new page for note 'Note'
WARNING: Failed to upload note 'Note' to Notion! Retrying...
DEBUG: Creating new page for note 'Note'
```

**Comment by vzhd1701** [comment]
Does this also happen with the notebooks that you've already uploaded?

**Comment by lbossle** [comment]
Yes, I get the same error message with notebooks I already uploaded successfully.

**Comment by lbossle** [comment]
It starts the progress bar like in this example:
`DEBUG: Creating new page for note 'Note'
  3%|█▎                                       | 2/63 [00:02<01:04,  1.06s/block]WARNING: id='438c67e9-932d-4b2f-9666-d9b2049268a2', type='table_row' does not have attribute 'title_plaintext' to be set; skipping.
WARNING: id='6e7a4015-d8c5-46f7-8cf3-bc246d6b4d0d', type='table_row' does not have attribute 'title_plaintext' to be set; skipping.
WARNING: Failed to upload note 'Note' to Notion! Retrying...`

**Comment by vzhd1701** [comment]
Could you share one of the notes that fail to upload?

**Comment by lbossle** [comment]
Sure, the notebook contains only one note.

[Note.zip](https://github.com/vzhd1701/enex2notion/files/8831885/Note.zip)

This is the command I used to upload
`.\enex2notion.exe --verbose --token #### .\Macarons.enex`

**Comment by vzhd1701** [comment]
Fixed. Please check out then new version.

**Comment by lbossle** [comment]
Thanks for the quick fix!
