### ISSUE TITLE
[Feature request]:  can not import chinese “印象笔记” 's notes(*.notes)

### ISSUE THREAD

**Issue by zenghao0708** [vzhd1701/enex2notion#41]
### Suggestion

Hello,

I am using chinese evernote(a.k.a "印象笔记")， and now it's exported notes(*.notes) is different from evernote's enex.

Is there any way to migrate *.notes to notion?

PS: when i rename the "*.notes" to "*.enex" and use the migrate tool, it has encountered an error:

Mac M1 Chipset, MACOS 12.4
Python 3.9.13
enex2notion: 0.2.16

> 
> INFO: 'Evernote ENEX Import' page found
> INFO: Processing notebook 'note'...
> Traceback (most recent call last):
>   File "/opt/homebrew/bin/enex2notion", line 8, in <module>
>     sys.exit(main())
>   File "/opt/homebrew/Cellar/enex2notion/0.2.16/libexec/lib/python3.10/site-packages/enex2notion/cli.py", line 47, in main
>     cli(sys.argv[1:])
>   File "/opt/homebrew/Cellar/enex2notion/0.2.16/libexec/lib/python3.10/site-packages/enex2notion/cli.py", line 32, in cli
>     _process_input(enex_uploader, args.enex_input)
>   File "/opt/homebrew/Cellar/enex2notion/0.2.16/libexec/lib/python3.10/site-packages/enex2notion/cli.py", line 42, in _process_input
>     enex_uploader.upload_notebook(path)
>   File "/opt/homebrew/Cellar/enex2notion/0.2.16/libexec/lib/python3.10/site-packages/enex2notion/cli_upload.py", line 55, in upload_notebook
>     for note_idx, note in enumerate(iter_notes(enex_file), 1):
>   File "/opt/homebrew/Cellar/enex2notion/0.2.16/libexec/lib/python3.10/site-packages/enex2notion/enex_parser.py", line 27, in iter_notes
>     yield from (_process_note(e) for e in iter_xml_elements_as_dict(enex_file, "note"))
>   File "/opt/homebrew/Cellar/enex2notion/0.2.16/libexec/lib/python3.10/site-packages/enex2notion/enex_parser.py", line 27, in <genexpr>
>     yield from (_process_note(e) for e in iter_xml_elements_as_dict(enex_file, "note"))
>   File "/opt/homebrew/Cellar/enex2notion/0.2.16/libexec/lib/python3.10/site-packages/enex2notion/enex_parser.py", line 52, in _process_note
>     is_webclip=_is_webclip(note_raw),
>   File "/opt/homebrew/Cellar/enex2notion/0.2.16/libexec/lib/python3.10/site-packages/enex2notion/enex_parser.py", line 75, in _is_webclip
>     re.search(
>   File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 200, in search
>     return _compile(pattern, flags).search(string)
> TypeError: expected string or bytes-like object 

Thanks,
Howie

**Comment by zenghao0708** [comment]
Found on my other M1 Mac, 『印象笔记』App can export enex file, so i decide to chose this proposal.

**Comment by Jface001** [comment]
@zenghao0708  I have a some problem，How to solve it?
<img width="491" alt="image" src="https://user-images.githubusercontent.com/21217483/180638407-becc3bf6-58a8-4322-8caf-137887012e3c.png">
