### ISSUE TITLE
How do I donate to you?

### ISSUE THREAD

**Issue by borwick** [vzhd1701/enex2notion#45]
### Suggestion

Hello! Your tool is great! FYI I just wrote about using it at https://www.johnborwick.com/2022/07/31/leaving-evernote.html . I would like to donate a small amount to you. I do not see any options in the README. What is a good way to do that?
Thanks!

**Comment by vzhd1701** [comment]
My repository has a "Sponsor" button which will lead you to my [buymeacoffee](https://www.buymeacoffee.com/vzhd1701) page.

Thank you for commending my tool in your article, this is more than a donation to be honest. Thank you so much for bringing exposure to my work, I really appreciate it! :)
