### ISSUE TITLE
"data" attribute not exist in resource_raw

### ISSUE THREAD

**Issue by suanmiao** [vzhd1701/enex2notion#48]
Hi,

I am reporting an edge case with the script, which I encountered when uploading my enex file. Below are the details: 
In this line https://github.com/vzhd1701/enex2notion/blob/master/enex2notion/enex_parser.py#L95 , the resource_raw sometimes doesn't have the "data" attribute, thus before getting the "data", it's better to check if that key exist, I did that local change and it works very well so far. 

Besides that, I really want to express my appreciation for the work you've done. This is an amazing tool! I've been using Evernote for 11 years, and have been paying them for 8+ years. Evernote used to be a simple, useful tool. But now it's basically a piece of sh*t, I can't even open their app successfully, you saved my day!

Quinn

**Comment by vzhd1701** [comment]
Thank you for the hint! Fix is in now, release will follow shortly.
