### ISSUE TITLE
[Bug]: Failed to resolve resource

### ISSUE THREAD

**Issue by mbdiener** [vzhd1701/enex2notion#53]
### enex2notion version

0.2.21

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 11

### Bug description

First, thanks so much for this utility!

I ran the Notion import against a test Notebook of 50 notes which have a combination of webclips and pdf attachments. Of the 50, only 14 uploaded. Running in verbose mode, I find that all of the rest have the message "Failed to Resolve Resource in 'notename' "

These notes are quite old, from 2014, and I notice that all the failed ones have attached files with Untitled Attachment as the title in the EN titlebar. Is this possibly what's causing the errors? If so, do you know any way to resolve this?

Thanks!

### Log excerpt

```shell
Parsing note 'Pedals for Progress Contrib'
DEBUG: Failed to resolve resource in 'Pedals for Progress Contrib'
DEBUG: Skipping note 'Pedals for Progress Contrib' (no blocks)
DEBUG: Parsing note 'AWJS Contribution'
DEBUG: Failed to resolve resource in 'AWJS Contribution'
DEBUG: Skipping note 'AWJS Contribution' (no blocks)
DEBUG: Parsing note 'Bend The Arc Contribution'
DEBUG: Failed to resolve resource in 'Bend The Arc Contribution'
DEBUG: Skipping note 'Bend The Arc Contribution' (no blocks)
DEBUG: Parsing note 'Receipt Just Vision Inc - mbdiener@gmail.com - Gmail'
DEBUG: Parsing note 'Verizon 1099 DIV'
DEBUG: Failed to resolve resource in 'Verizon 1099 DIV'
DEBUG: Skipping note 'Verizon 1099 DIV' (no blocks)
DEBUG: Parsing note 'Computer Receipt - Cyber Knight Computers'
DEBUG: Failed to resolve resource in 'Computer Receipt - Cyber Knight Computers'
DEBUG: Skipping note 'Computer Receipt - Cyber Knight Computers' (no blocks)
DEBUG: Parsing note 'Donation Confirmation - Heifer International - mbdiener@gmail.com - Gmail'
DEBUG: Parsing note 'Shame by JDB'
DEBUG: Failed to resolve resource in 'Shame by JDB'
```

**Comment by vzhd1701** [comment]
Could you please share any of the notes that are triggering "Failed to resolve resource" error?

**Comment by mbdiener** [comment]
[Pedals for Progress Contrib.zip](https://github.com/vzhd1701/enex2notion/files/9746617/Pedals.for.Progress.Contrib.zip)

I sent an email indicating that I couldn't attach the .enex file but then realized that I could zIp it and attach here. Here's one note that was showing the failed to resolve resource error. I did notice that they all only had attachments with no additional text so perhaps that the issue? 

Thanks!

**Comment by vzhd1701** [comment]
Fixed. Please check out the new version.

**Comment by mbdiener** [comment]
Bug has been fixed and now works great. Thank you!
