### ISSUE TITLE
[Bug]: yinxiang markdown block

### ISSUE THREAD

**Issue by BestVIncent** [vzhd1701/enex2notion#57]
### enex2notion version

latest

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10

### Bug description

The end of notion notes is always garbled。
![image](https://user-images.githubusercontent.com/46981434/195894937-bf1ba5c5-4619-4870-adbe-e84ba937ad36.png)
![image](https://user-images.githubusercontent.com/46981434/195895024-c9b5499c-77fd-4666-9917-24f1c21e52f3.png)

**Comment by vzhd1701** [comment]
Could you please share any of the notes that is causing this?

**Comment by BestVIncent** [comment]
Here is the notion link of my problem notes：https://www.notion.so/Docker-6528d3a0c7f141f790de3337b1f22bf1
And the enex file：https://1drv.ms/u/s!Ar1_SsPXoXZ_sy5cZqe1SAVIBGMb?e=5sbb3N
There is no any display problem in Enernote.

**Comment by vzhd1701** [comment]
I looked at your enex file. It seems like Yinxiang is appending hidden block to some notes which repeats note's content but in markdown format. I'll add fix to skip those blocks during parsing.

**Comment by vzhd1701** [comment]
Fixed. Please check out the new version and tell how it works for you.

**Comment by Ma-hy** [comment]
> I looked at your enex file. It seems like Yinxiang is appending hidden block to some notes which repeats note's content but in markdown format. I'll add fix to skip those blocks during parsing.

Hi, I found a exception in the new code, lots of notes meet **"AttributeError: 'NavigableString' object has no attribute 'attrs'"** in the new function **_filter_yinxiang_markdown()**

I think it still caused by Yinxiang's format problem, and here's my test enex file: https://1drv.ms/u/s!AhqI0UmA43o2g8hZKNWYNALG7kTFbg?e=thad6w   
sorry the content is in Chinese.

**Comment by vzhd1701** [comment]
@Ma-hy Fixed, thank you for reporting it. Check out the new version.

**Comment by Ma-hy** [comment]
Amazing thanks! It works great!
