### ISSUE TITLE
[Feature request]: Migrate To-do lists

### ISSUE THREAD

**Issue by patrickplaggenborg** [vzhd1701/enex2notion#7]
### Suggestion

Evernote supports the use of checkboxes to make lists of todos.
Notion also supports this as `To-do list` blocks

These are migrated as text blocks right now, and lose the [] checkbox in front of them.

Would it be possible to recreate todo checkboxes from Evernote as `To-do list` blocks in Notion?

**Comment by vzhd1701** [comment]
Those are supposed to migrate properly. Could you share an sample note or just a fragment of that note for which they are migrating as plain text?

**Comment by patrickplaggenborg** [comment]
Sure. I've added it to this debug file:
[Debug.enex.zip](https://github.com/vzhd1701/enex2notion/files/7661495/Debug.enex.zip)

**Comment by vzhd1701** [comment]
**Done**. Please check out the new version!
