### ISSUE TITLE
[Bug]: ERROR: Invalid token provided!

### ISSUE THREAD

**Issue by jiqiujia** [vzhd1701/enex2notion#78]
### enex2notion version

 0.2.25

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10

### Bug description

I run the following command 
`.\enex2notion.exe --done-file D:\done.txt --token [MY_TOKEN] D:\evernote\*.enex`
 and only get a error message 
`ERROR: Invalid token provided!`
![image](https://user-images.githubusercontent.com/8109984/227702236-254b07de-b27b-4443-b768-478c75fd4164.png)

**Comment by b-lazem** [comment]
Alas I'm facing the same issue

**Comment by b-lazem** [comment]
Hi @vzhd1701 it's `0.2.25` 

> What enex2notion version are you using?

**Comment by vzhd1701** [comment]
Try updating to 0.2.26, there was a bug that caused this error.

**Comment by b-lazem** [comment]
That fixed it! 💯 Thanks a ton!
