### ISSUE TITLE
[Bug]:  No imported pages in Notion

### ISSUE THREAD

**Issue by nghuyong** [vzhd1701/enex2notion#90]
### enex2notion version

0.2.26

### What OS are you using?

MacOS

### OS Version / Linux distribution

Mac OS 13.2.1

### Bug description

I successful run the import command, 

<img width="1857" alt="image" src="https://github.com/vzhd1701/enex2notion/assets/16462374/2bcdc138-3274-4713-8e18-2b11f6c46306">

but, I don't find the import page (Evernote ENEX Import) in the notion and don't find the imported data.
<img width="1320" alt="image" src="https://github.com/vzhd1701/enex2notion/assets/16462374/6f88c0a1-1361-47d7-8381-fa3155477025">

**Comment by vzhd1701** [comment]
Do you have other workspace at Notion?

**Comment by nghuyong** [comment]
@vzhd1701 
No, I have only one workspace

<img width="356" alt="image" src="https://github.com/vzhd1701/enex2notion/assets/16462374/f380ffb9-1993-4ebd-b3da-1ead095357de">

**Comment by vzhd1701** [comment]
Do you have another account?

**Comment by nghuyong** [comment]
ahhh, yes, I found them on another account ! !  
Thanks a lot !
