### ISSUE TITLE
[Bug]: Bad file descriptor when uploading attached images

### ISSUE THREAD

**Issue by klokie** [vzhd1701/enex2notion#98]
### enex2notion version

0.2.26

### What OS are you using?

Windows

### OS Version / Linux distribution

Mac OS Ventura

### Bug description

Hi, first of all let me say that this is a super helpful tool! Really appreciate your work here.
During upload of many years' worth of content, I've been getting a lot of `Bad file descriptor` errors. These do not appear during my dry runs (without the `token`), and I've had a hard time debugging them. The simple solution is to delete the image from Evernote and try again, but of course I'd like to preserve these images in Notion if possible.

please see sample note content at 
https://gist.github.com/klokie/1a815f5ad7e93c627925c84517d3d3e3#file-enex2notion-bad-file-descriptor-xml

### Log excerpt

```shell
please see log excerpt at 
https://gist.github.com/klokie/1a815f5ad7e93c627925c84517d3d3e3#file-traceback-log
```

**Comment by vzhd1701** [comment]
Seems like a network problem on your side. Do you have a proxy or some filtering firewall configured in your system? Can you reach s3.us-west-2.amazonaws.com directly?
```
curl -v "https://s3.us-west-2.amazonaws.com/"
```

**Comment by klokie** [comment]
Most images upload fine, but a few don't. I do have a firewall, but wouldn't that affect all content and not just a few images?

Here's the output; worth mentioning that I'm in Sweden.
https://app.warp.dev/block/KztObJ94IxcsmO44bm6fMY

**Comment by vzhd1701** [comment]
This is very strange indeed. I tested your note and it uploaded without problems on my side. Do you persistently get the errors on the same images when you retry?

**Comment by klokie** [comment]
It seems like there was in fact a firewall rule that must have been blocking that connection. Sorry about that! Thanks for the quick reply and the help.
